export const BOOKING_STAGES = [
  "started",
  "seats_held",
  "payment_pending",
  "confirmed",
  "waitlisted",
  "payment_failed",
  "expired",
  "cancelled",
] as const;

export type BookingStage = (typeof BOOKING_STAGES)[number];

export type ErrorShape = {
  code: string;
  message: string;
  canRetry: boolean;
};

export type Passenger = {
  name: string;
  age: number;
  gender: "male" | "female" | "other";
};

export type BookingRequest = {
  requestId: string; // generated by the frontend, so retries never double-book
  trainId: string;
  date: string; // "2026-12-25"
  from: string;
  to: string;
  passengers: Passenger[];
};

export type BookingResponse = {
  bookingId: string;
  stage: BookingStage;
  holdExpiresAt?: string;
};

export type HealthResponse = {
  status: "ok" | "broken";
  details: { database: boolean; redis: boolean };
};
