export type PaymentStatus =
  | "initiated"
  | "succeeded"
  | "failed"
  | "refund_pending"
  | "refunded";

export type PaymentStartResponse = {
  bookingId: string;
  paymentId: string;
  bankRef: string; // the bank's reference for this payment
  amountPaise: number;
  status: PaymentStatus;
};

export const BOOKING_STAGES = [
  "started",
  "seats_held",
  "payment_pending",
  "confirmed",
  "waitlisted",
  "payment_failed",
  "expired",
  "cancelled",
] as const;

export type BookingStage = (typeof BOOKING_STAGES)[number];

export type ErrorShape = {
  code: string;
  message: string;
  canRetry: boolean;
};

export type Passenger = {
  name: string;
  age: number;
  gender: "male" | "female" | "other";
};

export type BookingRequest = {
  requestId: string; // uuid generated by the frontend, so retries never double-book
  trainNumber: string;
  date: string;
  from: string; // station code
  to: string;
  class: string;
  passengers: Passenger[];
  waitlistIfFull?: boolean;
};

export type BookingResponse = {
  bookingId: string;
  stage: BookingStage;
  holdExpiresAt?: string;
  seats: { passenger: string; coach: string; seat: number }[];
  waitlistRequested: boolean;
  waitlistPosition?: number; // 1 = first in line
};

export type CancelResponse = {
  bookingId: string;
  stage: BookingStage;
  refundPaise: number;
  refundStatus: "none" | "refund_pending" | "refunded";
};

export type HealthResponse = {
  status: "ok" | "broken";
  details: { database: boolean; redis: boolean };
};

export type AvailabilityResponse = {
  trainNumber: string;
  date: string;
  from: string;
  to: string;
  class: string;
  segments: { first: number; last: number };
  availableCount: number;
  seats: { coach: string; seat: number }[];
};
